// Generated by https://quicktype.io
export interface LoginResponse {
  success:  boolean;
  response: Response;
}

export interface Response {
  id:              number;
  firstname:       string;
  lastname:        string;
  email:           string;
  photo:           string;
  phone:           string;
  facebook_id:     null;
  role:            number;
  created_at:      Date;
  updated_at:      Date;
  status:          number;
  is_notification: number;
  caption:         null;
  token_type:      string;
  access_token:    string;
}

